export const SETTINGS_GENERAL = "general"
export const SETTINGS_APPEARANCE = "appearance"
export const SETTINGS_RECORDER = "recorder"
export const SETTINGS_EXPORTER = "exporter"
export const SETTINGS_HOTKEYS = "hotkeys"
export const SETTINGS_STT = "stt"
export const SETTINGS_UPDATES = "updates"
