export const SETTINGS_GENERAL = "general"
export const SETTINGS_RECORDER = "recorder"
export const SETTINGS_EXPORTER = "exporter"
export const SETTINGS_LICENSE = "license"
export const SETTINGS_HOTKEYS = "hotkeys"
