export const VIDEO_SCHEME = "video"
export const SCREEN_VIDEO = "screen"
export const CAMERA_VIDEO = "camera"
export const MICROPHONE_AUDIO = "microphone"
export const RENDERED_VIDEO = "rendered"
export const RENDERED_VIDEO_WITH_AUDIO = "renderedWithAudio"
// Tauri v2 on Windows WebView2: custom protocols are accessed via http://<scheme>.localhost/
export const VIDEO_SCHEME_PREFIX = `http://${VIDEO_SCHEME}.localhost/`
export const IMAGE_SCHEME = "image"
export const IMAGE_SCHEME_PREFIX = `http://${IMAGE_SCHEME}.localhost/`
export const SCREEN_VIDEO_URL = `${VIDEO_SCHEME_PREFIX}${SCREEN_VIDEO}`
export const CAMERA_VIDEO_URL = `${VIDEO_SCHEME_PREFIX}${CAMERA_VIDEO}`
export const MICROPHONE_AUDIO_URL = `${VIDEO_SCHEME_PREFIX}${MICROPHONE_AUDIO}`
export const MODE_CAMERA_OVERLAY = "camera-overlay"
export const MODE_CAMERA_FULLSCREEN = "camera-fullscreen"
export const MODE_SCREEN_FULLSCREEN = "screen-fullscreen"
export const MODE_SIDE_BY_SIDE = "side-by-side"
export const POS_TOP_LEFT = { x: 0, y: 0 }
export const POS_TOP_RIGHT = { x: 1, y: 0 }
export const POS_BOTTOM_LEFT = { x: 0, y: 1 }
export const POS_BOTTOM_RIGHT = { x: 1, y: 1 }
export const SOURCE_TYPE_WINDOW = "window"
export const SOURCE_TYPE_SCREEN = "screen"
export const SOURCE_TYPE_AREA = "area"
export const RENDER_SCREEN_VIDEO = 'renderScreenVideo'
export const RENDER_CAMERA_VIDEO = 'renderCameraVideo'  
export const RENDER_OUTPUT_VIDEO = 'renderOutputVideo'  
export const PROJECT_SCREEN_VIDEO = 'projectScreenVideo'
export const PROJECT_CAMERA_VIDEO = 'projectCameraVideo'
export const PROJECT_MEDIA = 'projectMedia'
export const RECORDING_UNCORRECTED_CAMERA_VIDEO = 'recordingUncorrectedCameraVideo'
export const RECORDING_SCREEN_VIDEO = 'recordingScreenVideo'
export const RECORDING_CAMERA_VIDEO = 'recordingCameraVideo'
