export const EXPORT_PRESETS = [
    {
        id: "youtube-1080",
        name: "YouTube 1080p",
        icon: "yt",
        aspectRatio: "16x9",
        resolution: "1920x1080",
        fps: 30,
        quality: "high",
    },
    {
        id: "youtube-4k",
        name: "YouTube 4K",
        icon: "yt",
        aspectRatio: "16x9",
        resolution: "3840x2160",
        fps: 30,
        quality: "very_high",
    },
    {
        id: "tiktok",
        name: "TikTok / Reels",
        icon: "mobile",
        aspectRatio: "9x16",
        resolution: "1080x1920",
        fps: 30,
        quality: "high",
    },
    {
        id: "instagram-square",
        name: "Instagram Square",
        icon: "square",
        aspectRatio: "1x1",
        resolution: "1080x1080",
        fps: 30,
        quality: "high",
    },
    {
        id: "twitter",
        name: "Twitter / X",
        icon: "desktop",
        aspectRatio: "16x9",
        resolution: "1280x720",
        fps: 30,
        quality: "medium",
    },
    {
        id: "presentation",
        name: "Presentation",
        icon: "desktop",
        aspectRatio: "16x9",
        resolution: "1920x1080",
        fps: 30,
        quality: "medium",
    },
]
